server:
    id: "4536c604-ff15-4315-a95c-8eee866ce266"
    name: "HP Jet Fusion 5200"
    port: 8080
    printSpeed: 100
    apiPathPrefix: "/"
    writeTimeout: 15
    readTimeout: 15
    idleTimeout: 15
    allowedMethods: "GET, HEAD, POST, PUT, DELETE, OPTIONS"
    allowedOrigins: "*"
mqttBroker:
    host: "104.155.88.150"
    port: 1883
logger:
    verbose: true
